routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('welcome');
});

//Auth::routes();
Route::resource('/home', 'HomeController');
Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

Route::resource('profile', 'ProfileController');
Route::get('/profile/images/{id}', ['as' => 'profile.images', 'uses' => 'ProfileController@companyImages']);
Route::resource('search', 'SearchController');
Route::post('/vehicle/search', ['as' => 'vehicle.search', 'uses' => 'SearchController@search']);
Route::resource('/compare', 'CompareController');
Route::post('/vehicle/compare1', 'CompareController@secondCompare');
Route::post('/vehicle/compare', ['as' => 'vehicle.compare', 'uses' => 'CompareController@compare']);
Route::resource('/stared', 'StaredController');
Route::resource('/contact', 'ContactController');
Route::resource('/used', 'UsingController');
Route::resource('/about-us', 'AboutUsController');
Route::resource('/vehicle', 'VehicleController');
Route::get('/vehicle/delete/{id}', ['as' => 'vehicle.delete', 'uses' => 'VehicleController@destroy']);
Route::resource('/all-vehicle', 'VehicleShopController');
Route::resource('/model', 'ModelsController');
//Route::get('/make/model/{id}', 'CompareController@secondCompare');
Route::resource('/make', 'MakeController');
Route::get('/media/{id}','MediaController@destroy');
Route::post('/media/images', ['as' => 'media.images', 'uses' => 'MediaController@addMoreImages']);
Route::get('/media/image/{id}', 'MediaController@getImage');
Route::resource('media', 'MediaController');
Route::resource('more', 'MoreController');
//Route::put('/vec-seller/edit/{id}', ['as' => 'vec-seller.update', 'uses' => 'VehicleSellerController@update']);
Route::resource('vec-seller', 'VehicleSellerController');
Route::get('/vec-seller/images/{id}', ['as' => 'vec-seller.images', 'uses' => 'VehicleSellerController@vehicleImages']);
Route::get('/vec-seller/information/{id}', ['as' => 'vec-seller.information', 'uses' => 'VehicleSellerController@vehicleInformation']);
Route::get('/vec-seller/all/{id}', ['as' => 'vec-seller.all', 'uses' => 'VehicleSellerController@vehicleAllImages']);
Route::post('/vec-seller/images/{id}', ['as' => 'vec-seller.images', 'uses' => 'VehicleSellerController@store']);
Route::get('/seller', 'SellerController@index')->name('seller');
Route::post('/seller', 'SellerController@create');
Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	//Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::patch('/profile/update/{user}', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::patch('/profile/password/{user}', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

resources/views/layouts/navbars/auth.blade.php
<script src="{{url('/js/jquery.min.js')}}"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<style>

.navbar {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -ms-flex-align: center;
    align-items: center;
    -ms-flex-pack: justify;
    justify-content: space-between;
    padding: 5px;
}

/*
headeer top
*/
.topbar{
  background-color: #212529;
  padding: 0;
}

.topbar .container .row {
  margin:-7px;
  padding:0;
}

.topbar .container .row .col-md-12 { 
  padding:0;
}

.topbar p{
  margin:0;
  display:inline-block;
  font-size: 13px;
  color: #f1f6ff;
}

.topbar p > i{
  margin-right:5px;
}
.topbar p:last-child{
  text-align:right;
} 

header .navbar {
    margin-bottom: 0;
}

.topbar li.topbar {
    display: inline;
    padding-right: 18px;
    line-height: 52px;
    transition: all .3s linear;
}

.topbar li.topbar:hover {
    color: #1bbde8;
}

.topbar ul.info i {
    color: #131313;
    font-style: normal;
    margin-right: 8px;
    display: inline-block;
    position: relative;
    top: 4px;
}

.topbar ul.info li {
    float: right;
    padding-left: 30px;
    color: #ffffff;
    font-size: 13px;
    line-height: 44px;
}

.topbar ul.info i span {
    color: #aaa;
    font-size: 13px;
    font-weight: 400;
    line-height: 50px;
    padding-left: 18px;
}

ul.social-network {
  border:none;
  margin:0;
  padding:0;
}

ul.social-network li {
  border:none;  
  margin:0;
}

ul.social-network li i {
  margin:0;
}

ul.social-network li {
    display:inline;
    margin: 0 5px;
    border: 0px solid #2D2D2D;
    padding: 5px 0 0;
    width: 32px;
    display: inline-block;
    text-align: center;
    height: 32px;
    vertical-align: baseline;
    color: #000;
}

ul.social-network {
  list-style: none;
  margin: 5px 0 10px -25px;
  float: right;
}



.waves-effect {
    position: relative;
    cursor: pointer;
    display: inline-block;
    overflow: hidden;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
    vertical-align: middle;
    z-index: 1;
    will-change: opacity, transform;
    transition: .3s ease-out;
    color: #fff;
}
a {
  color: #0a0a0a;
  text-decoration: none;
}

li {
    list-style-type: none;
}
.bg-image-full {
    background-position: center center;
    background-repeat: no-repeat;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
}
.bg-dark {
    background-color: #222!important;
}

.mx-background-top-linear {
    background: -webkit-linear-gradient(45deg, #ffffff 48%, #1b1e21 48%);
    background: -webkit-linear-gradient(left, #ffffff 48%, #1b1e21 48%);
    background: linear-gradient(45deg, #ffffff 48%, #1b1e21 48%);
}

@media(min-width: 768px) {
    .navbar .navbar-nav {
        float: right;
    }
}
</style>

<div class="fixed-top">
    <header class="topbar">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="social-network">
                        <li>
                            <a class="waves-effect waves-dark" href="https://www.facebook.com/Auto-and-drive-102747047769028/">
                                <i style="color:#0062ff" class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="https://www.instagram.com/autoand.drive/">
                                <i style="color:#ff0080" class="fa fa-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a class="waves-effect waves-dark" href="#">
                                <i style="color:#33cc33" class="fa fa-whatsapp"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark mx-background-top-linear">
        <div class="container">
            <img src="{{url('/logo.png')}}" width=45>  
            <a class="navbar-brand" rel="nofollow" target="_blank" href="{{ route('home') }}" 
                style="color:black"> AutoAndDrive
            </a>
            <button class="navbarResponsiveButton navbar-toggler" id="navbarResponsiveButton" type="button" 
            data-toggle="collapse" data-target="#navbarResponsive"
             aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbarResponsiveMobile collapse navbar-collapse" id="navbarResponsive" style="visibility: hidden;">
                <ul class="navbar-nav ml-auto">  
                    <li class="nav-item active">
                        @auth()
                        <a class="nav-link" href="{{ route('home') }}">
                            <span></span>  {{ Auth::user()->name }}
                            <i class="material-icons">perm_identity</i> 
                        </a>
                        @endauth
                    </li>
                    <li class="nav-item"  id="homeLink">
                        <a class="nav-link" href="{{ route('home') }}">
                            <span></span>  الرئيسية
                            <i class="material-icons">home</i> 
                        </a>
                    </li>
                    <li class="nav-item" id="searchLink">
                        <a class="nav-link" href="{{ route('search.index') }}">
                            <span ></span>  البحث 
                            <i class="material-icons">search</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('vehicle.index') }}">
                            <span> </span>  الاِضافة
                            <i class="material-icons">post_add</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('compare.index') }}"> 
                            <span></span> المقارنة 
                            <i class="material-icons">compare</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('stared.index') }}"> 
                            <span></span> المميزة 
                            <i class="material-icons">star_half</i> 
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('more.index') }}"> 
                            <span ></span> المزيد 
                            <i class="material-icons">more_vert</i>
                        </a>
                    </li>
                </ul>
            </div>
            
            <div class="navbarResponsiveWeb collapse navbar-collapse " id="navbarResponsive">
                <ul class="navbar-nav ml-auto">   
                
                    <li class="nav-item ">
                        <a class="nav-link" href="{{ route('more.index') }}"> 
                            <span ></span> المزيد 
                            <i class="material-icons">more_vert</i>
                        </a>
                    </li>

                    <li class="nav-item ">
                        <a class="nav-link" href="{{ route('stared.index') }}"> 
                            <span></span> المميزة 
                            <i class="material-icons">star_half</i> 
                        </a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('compare.index') }}"> 
                            <span></span> المقارنة 
                            <i class="material-icons">compare</i>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('vehicle.index') }}">
                            <span> </span>  الاِضافة
                            <i class="material-icons">post_add</i>
                        </a>
                    </li>

                    <li class="nav-item" id="searchLink">
                        <a class="nav-link" href="{{ route('search.index') }}">
                            <span ></span>  البحث 
                            <i class="material-icons">search</i>
                        </a>
                    </li>

                    <li class="nav-item"  id="homeLink">
                        <a class="nav-link" href="{{ route('home') }}">
                            <span></span>  الرئيسية
                            <i class="material-icons">home</i> 
                        </a>
                    </li>
                    <li class="nav-item active">
                        @auth()
                        <a class="nav-link" href="{{ route('home') }}">
                            <span></span>  {{ Auth::user()->name }}
                            <i class="material-icons">perm_identity</i> 
                        </a>
                        @endauth
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

<script>

  
    var url = window.location.href;
    var arr = url.split('http://')[0];

    if (url.indexOf("search") >= 0) {

        $("#homeLink").css('display','block');
        $("#searchLink").css('display','none');
    } else if (url.indexOf("home") >= 0 || arr.indexOf("") == 0) {

        $("#searchLink").css('display','block');
        $("#homeLink").css('display','none');
    }
    
    $(window).resize(function() {
        if ($(this).width() < 500) {
            $('.navbarResponsiveWeb').css("display", "none");
            $('.navbarResponsiveMobile').css("visibility", "visible");
        } else if ($(this).width() > 500) {
            $('.navbarResponsiveWeb').css("display", "block");
            $('.navbarResponsiveMobile').css("visibility", "hidden");
        }
    });

</script>

resources/views/layouts/navbars/fixed-plugin-js.blade.php
<script>
    $(document).ready(function () {
        $('#facebook').sharrre({
            share: {
                facebook: true
            },
            enableHover: false,
            enableTracking: false,
            enableCounter: false,
            click: function (api, options) {
                api.simulateClick();
                api.openPopup('facebook');
            },
            template: '<i class="fab fa-facebook-f"></i> Facebook',
            url: 'https://demos.creative-tim.com/paper-dashboard/examples/dashboard.html'
        });
        $('#google').sharrre({
            share: {
                googlePlus: true
            },
            enableCounter: false,
            enableHover: false,
            enableTracking: true,
            click: function (api, options) {
                api.simulateClick();
                api.openPopup('googlePlus');
            },
            template: '<i class="fab fa-google-plus"></i> Google',
            url: 'https://demos.creative-tim.com/paper-dashboard/examples/dashboard.html'
        });
        $('#twitter').sharrre({
            share: {
                twitter: true
            },
            enableHover: false,
            enableTracking: false,
            enableCounter: false,
            buttons: {
                twitter: {
                    via: 'CreativeTim'
                }
            },
            click: function (api, options) {
                api.simulateClick();
                api.openPopup('twitter');
            },
            template: '<i class="fab fa-twitter"></i> Twitter',
            url: 'https://demos.creative-tim.com/paper-dashboard/examples/dashboard.html'
        });
        // Facebook Pixel Code Don't Delete
        ! function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window,
            document, 'script', '//connect.facebook.net/en_US/fbevents.js');
        try {
            fbq('init', '111649226022273');
            fbq('track', "PageView");
        } catch (err) {
            console.log('Facebook Track Error:', err);
        }
    });
</script>
<script>
    $(document).ready(function () {
        $sidebar = $('.sidebar');
        $sidebar_img_container = $sidebar.find('.sidebar-background');
        $full_page = $('.full-page');
        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        window_width = $(window).width();
        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();
        // if( window_width > 767 && fixed_plugin_open == 'Dashboard' ){
        //     if($('.fixed-plugin .dropdown').hasClass('show-dropdown')){
        //         $('.fixed-plugin .dropdown').addClass('show');
        //     }
        //
        // }
        $('.fixed-plugin a').click(function (event) {
            // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
            if ($(this).hasClass('switch-trigger')) {
                if (event.stopPropagation) {
                    event.stopPropagation();
                } else if (window.event) {
                    window.event.cancelBubble = true;
                }
            }
        });
        $('.fixed-plugin .active-color span').click(function () {
            $full_page_background = $('.full-page-background');
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var new_color = $(this).data('color');
            if ($sidebar.length != 0) {
                $sidebar.attr('data-active-color', new_color);
            }
            if ($full_page.length != 0) {
                $full_page.attr('data-active-color', new_color);
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.attr('data-active-color', new_color);
            }
        });
        $('.fixed-plugin .background-color span').click(function () {
            $(this).siblings().removeClass('active');
            $(this).addClass('active');
            var new_color = $(this).data('color');
            if ($sidebar.length != 0) {
                $sidebar.attr('data-color', new_color);
            }
            if ($full_page.length != 0) {
                $full_page.attr('filter-color', new_color);
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.attr('data-color', new_color);
            }
        });
        $('.fixed-plugin .img-holder').click(function () {
            $full_page_background = $('.full-page-background');
            $(this).parent('li').siblings().removeClass('active');
            $(this).parent('li').addClass('active');
            var new_image = $(this).find("img").attr('src');
            if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                $sidebar_img_container.fadeOut('fast', function () {
                    $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                    $sidebar_img_container.fadeIn('fast');
                });
            }
            if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
                var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');
                $full_page_background.fadeOut('fast', function () {
                    $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                    $full_page_background.fadeIn('fast');
                });
            }
            if ($('.switch-sidebar-image input:checked').length == 0) {
                var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
                var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');
                $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
            }
            if ($sidebar_responsive.length != 0) {
                $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
            }
        });
        $('.switch-sidebar-image input').on("switchChange.bootstrapSwitch", function () {
            $full_page_background = $('.full-page-background');
            $input = $(this);
            if ($input.is(':checked')) {
                if ($sidebar_img_container.length != 0) {
                    $sidebar_img_container.fadeIn('fast');
                    $sidebar.attr('data-image', '#');
                }
                if ($full_page_background.length != 0) {
                    $full_page_background.fadeIn('fast');
                    $full_page.attr('data-image', '#');
                }
                background_image = true;
            } else {
                if ($sidebar_img_container.length != 0) {
                    $sidebar.removeAttr('data-image');
                    $sidebar_img_container.fadeOut('fast');
                }
                if ($full_page_background.length != 0) {
                    $full_page.removeAttr('data-image', '#');
                    $full_page_background.fadeOut('fast');
                }
                background_image = false;
            }
        });
        $('.switch-mini input').on("switchChange.bootstrapSwitch", function () {
            $body = $('body');
            $input = $(this);
            if (paperDashboard.misc.sidebar_mini_active == true) {
                $('body').removeClass('sidebar-mini');
                paperDashboard.misc.sidebar_mini_active = false;
                $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();
            } else {
                $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');
                setTimeout(function () {
                    $('body').addClass('sidebar-mini');
                    paperDashboard.misc.sidebar_mini_active = true;
                }, 300);
            }
            // we simulate the window Resize so the charts will get updated in realtime.
            var simulateWindowResize = setInterval(function () {
                window.dispatchEvent(new Event('resize'));
            }, 180);
            // we stop the simulation of Window Resize after the animations are completed
            setTimeout(function () {
                clearInterval(simulateWindowResize);
            }, 1000);
        });
    });
</script>