routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    return view('welcome');
});

//Auth::routes();
Route::resource('/home', 'HomeController');
Route::get('/', 'HomeController@index')->name('home');
Auth::routes();

Route::resource('profile', 'ProfileController');
Route::get('/profile/images/{id}', ['as' => 'profile.images', 'uses' => 'ProfileController@companyImages']);
Route::resource('search', 'SearchController');
Route::post('/vehicle/search', ['as' => 'vehicle.search', 'uses' => 'SearchController@search']);
Route::resource('/compare', 'CompareController');
Route::post('/vehicle/compare1', 'CompareController@secondCompare');
Route::post('/vehicle/compare', ['as' => 'vehicle.compare', 'uses' => 'CompareController@compare']);
Route::resource('/stared', 'StaredController');
Route::resource('/contact', 'ContactController');
Route::resource('/used', 'UsingController');
Route::resource('/about-us', 'AboutUsController');
Route::resource('/vehicle', 'VehicleController');
Route::get('/vehicle/delete/{id}', ['as' => 'vehicle.delete', 'uses' => 'VehicleController@destroy']);
Route::resource('/all-vehicle', 'VehicleShopController');
Route::resource('/model', 'ModelsController');
//Route::get('/make/model/{id}', 'CompareController@secondCompare');
Route::resource('/make', 'MakeController');
Route::get('/media/{id}','MediaController@destroy');
Route::post('/media/images', ['as' => 'media.images', 'uses' => 'MediaController@addMoreImages']);
Route::get('/media/image/{id}', 'MediaController@getImage');
Route::resource('media', 'MediaController');
Route::resource('more', 'MoreController');
//Route::put('/vec-seller/edit/{id}', ['as' => 'vec-seller.update', 'uses' => 'VehicleSellerController@update']);
Route::resource('vec-seller', 'VehicleSellerController');
Route::get('/vec-seller/images/{id}', ['as' => 'vec-seller.images', 'uses' => 'VehicleSellerController@vehicleImages']);
Route::get('/vec-seller/information/{id}', ['as' => 'vec-seller.information', 'uses' => 'VehicleSellerController@vehicleInformation']);
Route::get('/vec-seller/all/{id}', ['as' => 'vec-seller.all', 'uses' => 'VehicleSellerController@vehicleAllImages']);
Route::post('/vec-seller/images/{id}', ['as' => 'vec-seller.images', 'uses' => 'VehicleSellerController@store']);
Route::get('/seller', 'SellerController@index')->name('seller');
Route::post('/seller', 'SellerController@create');
Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	//Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::patch('/profile/update/{user}', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::patch('/profile/password/{user}', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/Vehicle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Vehicle extends Model
{
    protected $table = 'vehicles'; 
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'make_id', 'mould_id', 'body', 'extra_title', 'year_of_product', 'year_of_work', 'price', 
        'first_payment', 'price_type', 'power', 'hp', 'mileage', 'gear', 'fuel', 'drivetrain_system', 'drivetrain_type',
        'num_of_seats', 'vehicle_status', 'body_color', 'interior_color', 'customs_exemption', 'num_of_doors', 'origin',
        'license_date', 'previous_owners' , 'num_of_keys', 'desc', 'order_type', 'order', 'is_deleted', 'publish_status',
        'stared', 'slider_id', 'delete_at'
    ];
}

app/Http/Controllers/MoreController.php
<?php

namespace App\Http\Controllers;

use App\Make;
use App\Models;
use App\Vehicle;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class MoreController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Display all the static pages when authenticated
     *
     * @param array $makes, $firstMakes
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $sellers = DB::table('users')
            ->join('regions', 'users.seller_region_id', '=', 'regions.id')
            ->select('users.*', 'regions.name as city')
            ->where("group", "=", "se")
            ->get();

        return view('pages.more.index', compact('sellers'));
    }

    /**
     * Display all the static pages when authenticated
     *
     * @param int $id
     * @return array $makes
     */
    public function show($id) { 
  
      
    }

}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use App\Equipment;
use App\Make;
use App\Media;
use App\Models;
use App\User;
use App\Vehicle;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class VehicleController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Display all the static pages when authenticated
     *
     * @param array $makes, $firstMakes
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $makes = Make::all();
        $firstMakes = Make::all()->take(8);
        $user = Auth::user();

        return view('pages.vehicle.index', compact('makes', 'firstMakes', 'user'));
    }

    /**
     * Display all the static pages when authenticated
     *
     * @param array $models
     * @return \Illuminate\View\View
     */
    public function show($id) { 

        $ids =  Models::where('make_id', '=', $id)->pluck('id');
        $test =  Models::where('parent', '=', $ids)
            ->where('make_id', '=', NULL)
            ->get();

        $count= count($ids);
        $i = 0;
        $t =array();

        while ($i < $count) {
            $models = Models::where('parent', '=', $ids[$i])
                ->orWhere('id', '=', $ids[$i])
                ->get();
                array_push($t, $models);
                $models = json_encode($t);
            $i++;
        }

        return $models;
    }

    /**
     * Create a new vehicle.
     *
     * @param  Illuminate\Http\Request  $request
     * @return \App\Vehicle
     */
    protected function store(Request $request)
    {
        $user = Auth::user();
        $userId = $user->id;
        $maxVehicles = $user->max_vehicles;
        $isPuplish = $user->publish_status;
        $vehicleCount = Vehicle::where("user_id", $userId)->count();
        
        if ($isPuplish =="yes" && $vehicleCount < $maxVehicles) {

            $vehicle = new Vehicle;
            $vehicle->user_id = $userId;
            $vehicle->fill($request->all());
            $vehicle->save();

            $types = [
                'payment_method',
                'ext_int_sunroof',
                'ext_int_furniture',
                'ext_int_seats',			
                'ext_int_steering',
                'ext_int_screens',
                'ext_int_glass',
                'ext_int_other',
                'ext_ext_light',
                'ext_ext_mirrors',
                'ext_ext_rims',
                'ext_ext_cameras',
                'ext_ext_sensors',
                'ext_ext_other',
                'ext_gen_other'
            ];

            foreach ($types as $key => $type) {
                if(is_array($request->$type)) {
                    foreach ($request->$type as $key => $req) {
                        Equipment::create([
                            'equipment_value' => $req,
                            'equipment_type' => $type,
                            'vehicle_id' => $vehicle->id,
                        ]);
                    }
                }
                else {
                    Equipment::create([
                        'equipment_value' => $request->$type,
                        'equipment_type' => $type,
                        'vehicle_id' => $vehicle->id,
                    ]);	
                }
            }
            
            return $vehicle;

        } else {

            return response()->json('غير مسموح الاضافة');
            //return redirect()->back()->withErrors(['name' => 'غير مسموح الاضافة ']);
        }
        
    }

    /**
     * Create a new vehicle.
     *
     * @param  Illuminate\Http\Request  $request, $id
     * @return \App\Vehicle
     */
    protected function update(Request $request, $id)
    {

    }

    /**
     * Delete vehicle.
     *
     * @param  int $id
     * @return \Illuminate\View\View
     */
    public function destroy($id)
    {
        $vehicle = Vehicle::findOrFail($id);
        $vehicle->is_deleted = "yes";
        $vehicle->save();
        //$vehicle->delete();
        return back();
    }
}

resources/views/pages/more/vehicle/found.blade.php
@extends('layouts.app')

@section('content')

<style>
.has-search .form-control {
    padding-right: 2.375rem;
}

.has-search .form-control-feedback {
    position: absolute;
    z-index: 2;
    display: block;
    width: 2.375rem;
    height: 2.375rem;
    line-height: 2.375rem;
    text-align: center;
    pointer-events: none;
    color: #aaa;
}

.main {
    width: 50%;
    margin: 50px auto;
}
</style>
    <div class="row"> 
        <div class="col-lg-1 col-md-1 col-sm-1">
        
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10">
            <center>
                <h5>
                المعارض
                </h5>
                <div class="row">
                    <div class="main col-lg-5 col-md-5 ml-auto mr-auto">
                        <div class="form-group has-search ">
                            <a href="{{route('all-vehicle.index')}}" style="cursor:pointer">
                                <span class="fa fa-arrow-right form-control-feedback"></span>
                                <input type="text" name="seller_name" class="form-control " value="{{$name}}">
                            </a>
                        </div>
                    </div>  
                </div> 
            </center>

            <div class="row">
                @foreach($sellers as $seller)
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <a href="{{route('all-vehicle.show', $seller->id)}}" class="text-muted">
                        <div class="card p-1 mb-1 bg-white rounded">
                            <div class="card-body ">
                                <div class="d-flex flex-row" style="padding: 0.4rem">
                                    <div style="width:100%; height: 150;" class="col-lg-6 col-md-6 col-sm-6">
                                        @if(!empty(\App\Media::where('fileable_id', '=', $seller->id)->select('file_name')->first()) > 0)
                                            <img class="img-responsive" style="width:100%; height: 150px;object-fit: contain"
                                                src="{{'/storage/sellers/'. (\App\Media::where('fileable_id', '=', $seller->id)->select('file_name')->first())->file_name}}">
                                        @endif
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="text-center row">
                                            <h6 style="color: black;font-size:14px">
                                                {{ $seller->seller_name }} 
                                            </h6>
                                        </div>
                                        <div class="row">
                                            <h6 style="color: gray;font-size:13px">
                                                {{ $seller->seller_mobile }} 
                                            </h6>
                                        </div></br>
                                        <div class="row">
                                            <h6 style="color: black;font-size:13px">
                                                {{ $seller->city }} , 
                                                <span style="color: gray;font-size:12px">
                                                    {{ $seller->seller_address }}
                                                </span>
                                            </h6>
                                        </div>
                                        <div class="row">
                                            <h6 style="color: gray; font-size:14px">
                                                {{ $seller->seller_email }} 
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <center>
                                            <div class="col-lg-6 col-md-6 col-sm-6">
                                                <form action="tel:{{ $seller->seller_mobile }} ">
                                                    <button class="btn btn-primary btn-block" style="cursor:pointer;background-color:#2e5cb8;color:white;padding:0.1rem" 
                                                        type="submit"><i class="fa fa-phone"></i> اٍتصل</button>
                                                </form>
                                            </div>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                @endforeach
            </div> 
        </div>
        <div class="col-lg-1 col-md-1 col-sm-1">
    
        </div>
    </div>
@endsection

resources/views/pages/more/vehicle/index.blade.php
@extends('layouts.app')

@section('content')

<style>
.has-search .form-control {
    padding-right: 2.375rem;
}

.has-search .form-control-feedback {
    position: absolute;
    z-index: 2;
    display: block;
    width: 2.375rem;
    height: 2.375rem;
    line-height: 2.375rem;
    text-align: center;
    pointer-events: none;
    color: #aaa;
}

.main {
    width: 50%;
    margin: 20px auto;
}
</style>
    <div class="row"> 
        <div class="col-lg-1 col-md-1 col-sm-1">
        
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10">
            <center>
                <h5>
                المعارض
                </h5>
                <div class="row">
                    <div class="main col-lg-5 col-md-5 ml-auto mr-auto">
                        <div class="form-group has-search ">
                            <form action="{{route('all-vehicle.store')}}" method="POST">
                                @csrf
                                <span class="fa fa-search form-control-feedback"></span>
                                <input type="text" name="seller_name" class="form-control " placeholder="بحث">
                                <button type="submit" hidden></button>
                            </form>
                        </div>
                    </div>  
                </div> 
            </center>

            <div class="row">
                @foreach($sellers as $seller)
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <a href="{{route('all-vehicle.show', $seller->id)}}" class="text-muted">
                        <div class="card p-1 mb-1 bg-white rounded">
                            <div class="card-body ">
                                <div class="d-flex flex-row" style="padding: 0.4rem">
                                    <div style="width:100%; height: 150;" class="col-lg-6 col-md-6 col-sm-6">
                                        @if(!empty(\App\Media::where('fileable_id', '=', $seller->id)->select('file_name')->first()) > 0)
                                            <img class="img-responsive" style="width:100%; height: 150px;object-fit: contain"
                                                src="{{'/storage/sellers/'. (\App\Media::where('fileable_id', '=', $seller->id)->select('file_name')->first())->file_name}}">
                                        @endif
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <div class="text-center row">
                                            <h6 style="color: black;font-size:14px">
                                                {{ $seller->seller_name }} 
                                            </h6>
                                        </div>
                                        <div class="row">
                                            <h6 style="color: gray;font-size:13px">
                                                {{ $seller->seller_mobile }} 
                                            </h6>
                                        </div></br>
                                        <div class="row">
                                            <h6 style="color: black;font-size:13px">
                                                {{ $seller->city }} , 
                                                <span style="color: gray;font-size:12px">
                                                    {{ $seller->seller_address }}
                                                </span>
                                            </h6>
                                        </div>
                                        <div class="row">
                                            <h6 style="color: gray; font-size:14px">
                                                {{ $seller->seller_email }} 
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <center>
                                            <div class="col-lg-6 col-md-6 col-sm-6">
                                                <form action="tel:{{ $seller->seller_mobile }} ">
                                                    <button class="btn btn-primary btn-block" style="cursor:pointer;background-color:#2e5cb8;color:white;padding:0.1rem" 
                                                        type="submit"><i class="fa fa-phone"></i> اٍتصل</button>
                                                </form>
                                            </div>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                @endforeach
            </div> 
        </div>
        <div class="col-lg-1 col-md-1 col-sm-1">
    
        </div>
    </div>
@endsection